openapi: 3.0.3
info:
  title: Customers API
  description: API for See Statistics Customer.
  version: 1.0.0
paths:
  /v1/admin/customers:
    get:
      summary: Get all customers
      description: Retrieve a list of customers with optional filters.
      tags:
        - Admin - Customers
      security:
        - BearerAuth: []
      parameters:
        - name: name
          in: query
          description: Filter by customer name
          required: false
          schema:
            type: string
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerBaseResponseDtoArray'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CustomerDto:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        transactionCount:
          type: integer
        createdAt:
          type: string
          format: date-time
      example:
        name: "John Doe"
        email: "john.doe@example.com"
        transactionCount: 5
        createdAt: "2023-01-01T00:00:00Z"
    CustomerBaseResponseDtoArray:
      type: object
      properties:
        status:
          type: string
        code:
          type: integer
        message:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/CustomerDto'
        paging:
          $ref: '#/components/schemas/Paging'
      example:
        status: success
        code: 200
        message: Customers retrieved successfully
        data:
          - name: "John Doe"
            email: "john.doe@example.com"
            transactionCount: 5
            createdAt: "2023-01-01T00:00:00Z"
          - name: "Jane Smith"
            email: "jane.smith@example.com"
            transactionCount: 3
            createdAt: "2023-01-02T00:00:00Z"
        paging:
          size: 10
          page: 1
          current_page: 1
          total_page: 2
    Paging:
      type: object
      properties:
        size:
          type: integer
        page:
          type: integer
        current_page:
          type: integer
        total_page:
          type: integer
      example:
        size: 10
        page: 1
        current_page: 1
        total_page: 2