services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: berkah-backend
    restart: unless-stopped
    ports:
      - "5001:5000"
      - "5555:5555"
    volumes:
      - ./storage:/app/storage
    env_file:
      - .env.production
    depends_on:
      - db
    networks:
      - berkah-network

  db:
    image: mysql:8.0.40
    container_name: berkah-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: berkah
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - berkah-network
    mem_limit: 1073741824 # 1GB memory limit

networks:
  berkah-network:
    driver: bridge

volumes:
  mysql_data: